name: "Gerar APK do ZIP"
on: [push]

jobs:
  export_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Extrair Projeto do ZIP
        run: unzip MysticFarmEmpire3D.zip

      - name: Exportar APK via Godot
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_export_output: true
        env:
          EXPORT_NAME: MysticFarmEmpire3D
          
